# PostgreSQL version 11.3
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: let_me_post_it_dev

test:
  <<: *default
  database: let_me_post_it_test

production:
  <<: *default
  database: let_me_post_it_production